name: project2
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - cftime=1.6.4
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - h5netcdf=1.2.0
  - joblib=1.4.2
  - matplotlib=3.10.3
  - netcdf4=1.6.5
  - numpy=1.24.4
  - pandas=2.3.0
  - petsc=3.21.1
  - petsc4py=3.21.1
  - pip
  - pytorch=2.6.0
  - scipy
  - shapely=2.1.1
  - suitesparse=5.10.1
  - tbb=2022.2.0
  - tqdm=4.66.5
  - xarray=2025.4.0
  - pip:
      - jax==0.4.25
      - jaxlib==0.4.25
